<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Start Of Execution(TEST)->Default test]]>
    </line>
    <line>
      <![CDATA[Test Started->m1]]>
    </line>
    <line>
      <![CDATA[Test Failed->m1]]>
    </line>
    <line>
      <![CDATA[Test Started->m3]]>
    </line>
    <line>
      <![CDATA[Test Pass->m3]]>
    </line>
  </reporter-output>
  <suite started-at="2020-12-04T05:55:44Z" name="Default suite" finished-at="2020-12-04T05:55:44Z" duration-ms="39">
    <groups>
    </groups>
    <test started-at="2020-12-04T05:55:44Z" name="Default test" finished-at="2020-12-04T05:55:44Z" duration-ms="39">
      <class name="com.seleniumprograms.testng.Testcase1">
        <test-method signature="m1()[pri:0, instance:com.seleniumprograms.testng.Testcase1@c7045b9]" started-at="2020-12-04T11:25:44Z" name="m1" finished-at="2020-12-04T11:25:44Z" duration-ms="10" status="FAIL">
          <exception class="java.lang.Error">
            <full-stacktrace>
              <![CDATA[java.lang.Error
	at com.seleniumprograms.testng.Testcase1.m1(Testcase1.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
            <line>
              <![CDATA[Test Started->m1]]>
            </line>
            <line>
              <![CDATA[Test Failed->m1]]>
            </line>
          </reporter-output>
        </test-method> <!-- m1 -->
        <test-method signature="m3()[pri:0, instance:com.seleniumprograms.testng.Testcase1@c7045b9]" started-at="2020-12-04T11:25:44Z" name="m3" finished-at="2020-12-04T11:25:44Z" duration-ms="2" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Test Started->m3]]>
            </line>
            <line>
              <![CDATA[Test Pass->m3]]>
            </line>
          </reporter-output>
        </test-method> <!-- m3 -->
      </class> <!-- com.seleniumprograms.testng.Testcase1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
